name: Build Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest



    steps:
      - uses: actions/checkout@v3
        with:
          ref: pages-build
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'pages-build'
      - name: Build React
        working-directory: ./examples/react
        run: |
            npm install
            npm run build
      - name: Build Svelte
        working-directory: ./examples/svelte
        run: |
            npm install
            npm run build
      - name: Build Solid
        working-directory: ./examples/solid
        run: |
            npm install
            npm run build
      - name: Build Vanilla
        working-directory: ./examples/vanilla
        run: |
            npm install
            npm run build
      - name: Copy React
        working-directory: ./
        run: |
            cp -a examples/react/dist .
            mv dist react
      - name: Copy Svelte
        working-directory: ./
        run: |
            cp -a examples/svelte/dist .
            mv dist svelte
      - name: Copy Solid
        working-directory: ./
        run: |
            cp -a examples/solid/dist .
            mv dist solid
      - name: Copy Vanilla
        working-directory: ./
        run: |
            cp -a examples/vanilla/dist .
            mv dist vanilla
      - name: Delete
        working-directory: ./
        run: |
            rm -r examples
            rm -r .github
            rm readme.md
            ls
      - name: Commit
        working-directory: ./
        run: | 
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Automatic Deploy action run by github-actions"
            git push origin HEAD:pages-build --force
            
            
